spring.application.name=Bookie
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DATABASE_NAME}
spring.datasource.password=${DATABASE_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.order_updates = true
spring.jpa.open-in-view=false
spring.flyway.enabled=false
spring.flyway.create-schemas=false

server.servlet.context-path=/api/v1


# security
application.security.jwt.secret-key = "this324is23at4es4tse43cre4tk3ey12f3d45sd678fd90!"
application.security.jwt.expiration = 600000